#!/usr/bin/env python3
"""Extract replayable DeciSearch workflow prompts from saved trajectories.

The paper's Exact-State DPO starts from fixed workflow states. This helper
extracts those fixed prompt states from `llm_messages_*.json` files generated by
`run.py`. A separate branch-rollout/scoring job can sample alternative next
responses from these prompts, resume the deterministic runtime, and score the
resulting final localization quality.

Output JSONL schema:

    {
      "id": "run:instance:0003:controller",
      "run_name": "...",
      "instance_id": "...",
      "component": "controller|worker|verifier|finalizer",
      "event": "state",
      "system": "...",
      "prompt": "...",
      "observed_response": "...",
      "observed_role": "gpt|function_call",
      "metadata": {...}
    }

`observed_response` is the next assistant message after the state prompt when it
exists. It is useful for auditing and SFT diagnostics, but Exact-State DPO should
label preferences from branch outcomes, not from the original observed response.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

STATE_COMPONENTS = {"controller", "worker", "verifier", "finalizer"}


def instance_id_from_file(path: Path) -> str:
    name = path.name
    prefix = "llm_messages_"
    suffix = ".json"
    if name.startswith(prefix) and name.endswith(suffix):
        return name[len(prefix) : -len(suffix)]
    return path.stem


def assistant_payload(message: dict[str, Any] | None) -> tuple[str, str]:
    if not message or message.get("role") != "assistant":
        return "", ""
    tool_calls = message.get("tool_calls") or []
    if tool_calls:
        payload = []
        for call in tool_calls:
            function = call.get("function") or {}
            payload.append(
                {
                    "name": function.get("name") or "",
                    "arguments": function.get("arguments") or "{}",
                }
            )
        return json.dumps(payload, ensure_ascii=False), "function_call"
    return message.get("content") or "", "gpt"


def extract_snapshots(path: Path, *, run_name: str, limit_per_instance: int | None = None) -> list[dict[str, Any]]:
    messages = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(messages, list):
        return []

    instance_id = instance_id_from_file(path)
    system = ""
    for message in messages:
        if isinstance(message, dict) and message.get("role") == "system":
            system = message.get("content") or ""
            break

    records: list[dict[str, Any]] = []
    for idx, message in enumerate(messages):
        if not isinstance(message, dict) or message.get("role") != "user":
            continue
        metadata = message.get("metadata") if isinstance(message.get("metadata"), dict) else {}
        if metadata.get("workflow") != "decisearch":
            continue
        component = metadata.get("component")
        if component not in STATE_COMPONENTS or metadata.get("event") != "state":
            continue

        next_message = messages[idx + 1] if idx + 1 < len(messages) and isinstance(messages[idx + 1], dict) else None
        observed_response, observed_role = assistant_payload(next_message)
        record = {
            "id": f"{run_name}:{instance_id}:{len(records):04d}:{component}",
            "run_name": run_name,
            "instance_id": instance_id,
            "component": component,
            "event": "state",
            "system": system,
            "prompt": message.get("content") or "",
            "observed_response": observed_response,
            "observed_role": observed_role,
            "metadata": metadata,
        }
        records.append(record)
        if limit_per_instance is not None and len(records) >= limit_per_instance:
            break
    return records


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", required=True, type=Path)
    parser.add_argument("--out", required=True, type=Path)
    parser.add_argument("--limit", type=int, default=None, help="Maximum number of trajectory files to read.")
    parser.add_argument("--limit-per-instance", type=int, default=None)
    args = parser.parse_args()

    if not args.run_dir.is_dir():
        raise FileNotFoundError(args.run_dir)
    args.out.parent.mkdir(parents=True, exist_ok=True)

    files = sorted(args.run_dir.glob("llm_messages_*.json"))
    if args.limit is not None:
        files = files[: args.limit]

    written = 0
    by_component: dict[str, int] = {}
    with args.out.open("w", encoding="utf-8") as f:
        for path in files:
            try:
                records = extract_snapshots(
                    path,
                    run_name=args.run_dir.name,
                    limit_per_instance=args.limit_per_instance,
                )
            except Exception as exc:
                print(f"skip {path.name}: {exc}")
                continue
            for record in records:
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
                written += 1
                by_component[record["component"]] = by_component.get(record["component"], 0) + 1

    print(json.dumps({"snapshots": written, "by_component": by_component, "out": str(args.out)}, indent=2))


if __name__ == "__main__":
    main()
